### ISSUE TITLE
ERROR TypeError: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by edurenye** [lando/drupal#116]
When I try to run any drush command I get an error with the drupal10 recipe.
I get the following error using `-vvv` option:
```
  lando emitting event ready  +7ms
  lando emitting event cli-answers  +1ms
  lando emitting event cli-drush-answers  +0ms
  lando emitting event cli-run  +0ms
  lando emitting event cli-drush-run  +1ms
  lando resolved tooling command drush service to app  +2ms
  lando emitting event pre-command-runner  +0ms
  lando emitting event pre-drush  +1ms
  lando ERROR TypeError: Cannot read properties of undefined (reading 'match')
    at parse (/snapshot/cli/node_modules/@lando/core/node_modules/yargs-parser/index.js:154:13)
    at Parser (/snapshot/cli/node_modules/@lando/core/node_modules/yargs-parser/index.js:855:16)
    at Shell.sh (/snapshot/cli/node_modules/@lando/core/lib/shell.js)
    at /snapshot/cli/node_modules/@lando/core/utils/build-docker-exec.js
    at /snapshot/cli/node_modules/@lando/core/utils/build-tooling-task.js
    at process.processImmediate (node:internal/timers:476:21)  +5ms
```

.lando.yml content:
```
name: test
recipe: drupal10
config:
  webroot: web
```
Drush version in composer: 11.6.0
Lando version: v3.21.0
All plugin are up to date.

**Comment by AaronFeledy** [comment]
@soniktrooth You have `cmd` indented too far. It shouldn't be nested in `env`.

**Comment by AaronFeledy** [comment]
Unable to replicate and the issue is not getting much traction. Closing for now.
