### ISSUE TITLE
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by JedrzejMarciniakDev** [lando/drupal#53]
OS: Win 11 Pro 22H2 / WSL2
Lando 3.6.11
Docker version 20.10.23, build 7155243
Docker Desktop 4.17.0 (99724)

Cant run any command with lando. It startet after composer update of drupal, drush and other packages
For lando version, init or start i get below error:

Unhandled rejection TypeError: Cannot read properties of undefined (reading 'split')
at /snapshot/cli/node_modules/@lando/platformsh/lib/config.js
at arrayMap (/snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js)
at Function.map (/snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js)
at interceptor (/snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js)
at Function.thru (/snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js)
at /snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js
at arrayReduce (/snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js)
at baseWrapperValue (/snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js)
at LodashWrapper.wrapperValue (/snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js)
at Object.getSyncableRelationships (/snapshot/cli/node_modules/@lando/platformsh/lib/config.js)
at AsyncEvents. (/snapshot/cli/node_modules/@lando/platformsh/app.js)
at AsyncEvents.handle (/snapshot/cli/node_modules/@lando/core/lib/events.js)
at /snapshot/cli/node_modules/@lando/core/lib/events.js
From previous event:
at AsyncEvents.emit (/snapshot/cli/node_modules/@lando/core/lib/events.js)
at /snapshot/cli/node_modules/@lando/core/lib/app.js
From previous event:
at App.init (/snapshot/cli/node_modules/@lando/core/lib/app.js)
at /snapshot/cli/bin/lando.js
at processImmediate (node:internal/timers:466:21)
From previous event:
at Object. (/snapshot/cli/bin/lando.js)
at Module._compile (pkg/prelude/bootstrap.js:1887:22)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
at node:internal/main/run_main_module:17:47

**Comment by reynoldsalec** [comment]
For future reference, many of these types of errors can be traced back to an issue in the user's `.lando.yml` file. If anyone gets here via Google, highly recommend posting your issue on the Lando Slack (https://www.launchpass.com/devwithlando) and including your `.lando.yml` for reference so you can get help debugging.
